version: "3.9"

services:
  app:
    build:
      context: . # docker will build an image for this service using the dockerfile in the current directory.
      args:
        - DEV=true
    ports:
      - "8000:8000" # Machine to container
    volumes:
      - ./app:/app # Any changes made to local will direclty reflects to the container
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"